name: Build TWRP image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Init repo
      run: |
        sudo apt-get install repo
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sync
      run: |
        repo sync --no-repo-verify -c --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune -jnproc

    - name: Clone common tree repo
      run: |
        git config --global user.email "guinnessgshep@gmail.com"
        git config --global user.name "Guinness Shepherd"
        git clone https://github.com/Peter-Levine/android_device_google_gs201 device/google/gs201-common

    - name: Clone tree
      run: |
        git clone https://github.com/Peter-Levine/android_device_google_cheetah device/google/cheetah

    - name: Build
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_cheetah-eng
        mka recoveryimage
