name: Build TWRP Image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Clone Common Tree Repo
        run: git clone https://github.com/Peter-Levine/android_device_google_gs201 device/google/gs201-common

      - name: Clone Tree
        run: git clone https://github.com/Peter-Levine/android_device_google_cheetah device/google/cheetah

      - name: Build
        run: |
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_cheetah-eng
          mka recoveryimage

      - name: Archive Recovery Image
        uses: actions/upload-artifact@v2
        with:
          name: twrp_recovery_image
          path: out/target/product/cheetah/recovery.img

      - name: Send Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,eventName
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
