name: Build TWRP

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Install Repo
      run: |
        mkdir -p $HOME/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
        chmod a+x $HOME/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH
        
    - name: Init Repo
      run: repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sync Repo
      continue-on-error: true
      run: repo sync --no-repo-verify -c --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune -j$(nproc)

    - name: Clone Common Tree Repo
      run: git clone https://github.com/Peter-Levine/android_device_google_gs201 device/google/gs201-common

    - name: Clone Tree
      run: git clone https://github.com/Peter-Levine/android_device_google_cheetah device/google/cheetah

    - name: Build
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_cheetah-eng
        mka recoveryimage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TWRP Image
        path: out/target/product/cheetah/recovery.img
